# Usar una imagen de Go como base para compilar el código
FROM golang:1.17 AS builder

# Configurar el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de código fuente al contenedor
COPY . .

# Instala la biblioteca CORS
RUN go get github.com/rs/cors

# Compila la aplicación Go
RUN go build -o myapp

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 3010

# Define el comando por defecto para ejecutar la aplicación
CMD ["./myapp"]

# docker build -t server .
# docker run -p 3010:3010  server