# Usar una imagen base de Node.js
FROM node:alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo package.json y package-lock.json al directorio de trabajo
COPY package.json .

# Instalar las dependencias del proyecto
RUN npm install

# Copiar el resto de los archivos del proyecto al directorio de trabajo
COPY . .

# Construir la aplicación React
RUN npm run build

# Exponer el puerto en el que se ejecutará la aplicación (si es necesario)
EXPOSE 5173

# Comando para iniciar la aplicación cuando se ejecute el contenedor
CMD ["npm", "run","dev"]

# docker build -t frontend .

### CORRER LA IMAGEN
### docker run -p 5173:5173 frontend